name: CI

# allow also running manually
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Run ESLint
        run: npm run eslint

      - name: Create archive
        run: tar -czf dist.tar.gz dist

      - name: Set PR release tag
        if: github.event_name == 'pull_request'
        id: pr_release_tag
        run: |
          head_ref=${{ github.head_ref }}
          sanitized_head_ref=$(echo "$head_ref" | sed 's|/|-|g')
          echo "tag_name=pr-${{ github.actor }}-${sanitized_head_ref}" >> $GITHUB_OUTPUT

      - name: Create PR release
        if: github.event_name == 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: "Build for PR #${{ github.event.pull_request.number }} by @${{ github.actor }}"
          tag_name: ${{ steps.pr_release_tag.outputs.tag_name }}
          files: dist.tar.gz
          prerelease: true
          overwrite: true

      - name: Release on merge to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: dist.tar.gz
          tag_name: latest
          overwrite: true
